apiVersion: v1
kind: Config
clusters:
- name: "agents"
  cluster:
    server: "https://rancher-server.echo.tech/k8s/clusters/c-m-t9nbx25w"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN4TWpVNApPRE15TkRBZUZ3MHlOREEwTURneE5EVTRORFJhRncwek5EQTBNRFl4TkRVNE5EUmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56RXlOVGc0TXpJME1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXUxbDRJVTRtTzJMdgp6eVBVV3g5RE5TY0JoWlBIN3I0elN6a203Z\
      TZGU1BHb1hwREMwbUlYaldWTTFXTkEvajNWR3NiaHE4WkdEU01jClZVOU96bkMzYjZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQ\
      VRHdUp0Z0xNbUt1RnRuUlV2Uzd0Y2FKRGtKTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUhMdgpMT\
      GlLU1JhZTVqOGpQSUE3VDR3YnQ2KzMyS09pN3dNdE04VWg0NlZ2QWlCU2V4UnZNYTNvZE1qUG9nU\
      E0wVVZHCm9aWDJjcGdBNjJQRS90b2NjdXhEbmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "agents"
  user:
    token: "kubeconfig-user-7mhtgmd9f6:whj7vp8rlswltlr69qpb8pt9vs7xlpqj4r4lxgcc7zfwkbxslsjsdz"


contexts:
- name: "agents"
  context:
    user: "agents"
    cluster: "agents"

current-context: "agents"
