apiVersion: v2
name: sac
description: SAC (Claude Code Sandbox) - Enterprise Web Terminal Platform
type: application
version: 0.1.0
appVersion: "0.0.11"

dependencies:
  - name: gateway-helm
    version: v1.6.3
    condition: envoyGateway.enabled
