apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "sac.labels" . | nindent 4 }}
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  type: ClusterIP
