{{- if .Values.envoyGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: sac
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: sac-proxy-config
    namespace: {{ .Release.Namespace }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sac-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: sac
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      {{- if .Values.envoyGateway.host }}
      hostname: {{ .Values.envoyGateway.host }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
