{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: sac-gateway
  labels:
    {{- include "sac.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- toYaml .Values.istio.gateway.hosts | nindent 8 }}
    {{- if .Values.istio.gateway.tls.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.istio.gateway.tls.credentialName }}
      hosts:
        {{- toYaml .Values.istio.gateway.hosts | nindent 8 }}
    {{- end }}
{{- end }}
