apiVersion: v1
kind: Secret
metadata:
  name: sac-secret
  labels:
    {{- include "sac.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.database.password | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
